#!/bin/bash
set -e

# Adds secrets to environment.
if [ -f /secrets/env.list ];
then
  set -a
  source /secrets/env.list
  set +a
fi

if [ -f /work/tmp/.run_bundle_update ];
then
  bundle update --jobs 3 --retry 3
fi

if [ -f /work/tmp/.run_bundle_install ];
then
  bundle install --jobs 3 --retry 3
fi

# Starts spring server if running in development.
if ! [[ "$1" == 'bash' || "$1" == '/bin/bash' ]];
then
  if [[ "$RAILS_ENV" == 'development' || "$RAILS_ENV" == '' ]];
  then
    if [ -z "$(ps aux | grep 'spring server' | grep -v 'grep')" ];
    then
      rake --help > /dev/null
    fi
  fi
fi

exec "$@"
